/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo Go Public API
 * Multi-tenant Todo Application with Row Level Security
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTodoRequest,
  ErrorResponse,
  TodoListResponse,
  TodoResponse,
  UpdateTodoRequest
} from '.././model';

import { customInstance } from '../../axios-instance';




/**
 * @summary List user's todos
 */
export const listTodos = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<TodoListResponse>(
      {url: `/todos`, method: 'GET', signal
    },
      );
    }
  



export const getListTodosQueryKey = () => {
    return [
    `/todos`
    ] as const;
    }

    
export const getListTodosQueryOptions = <TData = Awaited<ReturnType<typeof listTodos>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTodos>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTodosQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTodos>>> = ({ signal }) => listTodos(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTodosQueryResult = NonNullable<Awaited<ReturnType<typeof listTodos>>>
export type ListTodosQueryError = ErrorResponse


export function useListTodos<TData = Awaited<ReturnType<typeof listTodos>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTodos>>,
          TError,
          Awaited<ReturnType<typeof listTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTodos<TData = Awaited<ReturnType<typeof listTodos>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTodos>>,
          TError,
          Awaited<ReturnType<typeof listTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTodos<TData = Awaited<ReturnType<typeof listTodos>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTodos>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List user's todos
 */

export function useListTodos<TData = Awaited<ReturnType<typeof listTodos>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTodos>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTodosQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new todo
 */
export const createTodo = (
    createTodoRequest: CreateTodoRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TodoResponse>(
      {url: `/todos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTodoRequest, signal
    },
      );
    }
  


export const getCreateTodoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext> => {

const mutationKey = ['createTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTodo>>, {data: CreateTodoRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTodo(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof createTodo>>>
    export type CreateTodoMutationBody = CreateTodoRequest
    export type CreateTodoMutationError = ErrorResponse

    /**
 * @summary Create a new todo
 */
export const useCreateTodo = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTodo>>, TError,{data: CreateTodoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTodo>>,
        TError,
        {data: CreateTodoRequest},
        TContext
      > => {

      const mutationOptions = getCreateTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List public todos in tenant
 */
export const listPublicTodos = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<TodoListResponse>(
      {url: `/todos-public`, method: 'GET', signal
    },
      );
    }
  



export const getListPublicTodosQueryKey = () => {
    return [
    `/todos-public`
    ] as const;
    }

    
export const getListPublicTodosQueryOptions = <TData = Awaited<ReturnType<typeof listPublicTodos>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicTodos>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPublicTodosQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPublicTodos>>> = ({ signal }) => listPublicTodos(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPublicTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPublicTodosQueryResult = NonNullable<Awaited<ReturnType<typeof listPublicTodos>>>
export type ListPublicTodosQueryError = ErrorResponse


export function useListPublicTodos<TData = Awaited<ReturnType<typeof listPublicTodos>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicTodos>>,
          TError,
          Awaited<ReturnType<typeof listPublicTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublicTodos<TData = Awaited<ReturnType<typeof listPublicTodos>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicTodos>>,
          TError,
          Awaited<ReturnType<typeof listPublicTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublicTodos<TData = Awaited<ReturnType<typeof listPublicTodos>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicTodos>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List public todos in tenant
 */

export function useListPublicTodos<TData = Awaited<ReturnType<typeof listPublicTodos>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicTodos>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPublicTodosQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a todo
 */
export const updateTodo = (
    id: string,
    updateTodoRequest: UpdateTodoRequest,
 ) => {
      
      
      return customInstance<TodoResponse>(
      {url: `/todos/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateTodoRequest
    },
      );
    }
  


export const getUpdateTodoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: string;data: UpdateTodoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: string;data: UpdateTodoRequest}, TContext> => {

const mutationKey = ['updateTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTodo>>, {id: string;data: UpdateTodoRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTodo(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof updateTodo>>>
    export type UpdateTodoMutationBody = UpdateTodoRequest
    export type UpdateTodoMutationError = ErrorResponse

    /**
 * @summary Update a todo
 */
export const useUpdateTodo = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: string;data: UpdateTodoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTodo>>,
        TError,
        {id: string;data: UpdateTodoRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a todo
 */
export const deleteTodo = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/todos/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteTodoMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodo>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteTodo(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTodoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodo>>>
    
    export type DeleteTodoMutationError = ErrorResponse

    /**
 * @summary Delete a todo
 */
export const useDeleteTodo = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTodo>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    