/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo Go Public API
 * Multi-tenant Todo Application with Row Level Security
 * OpenAPI spec version: 1.0.0
 */

export interface RefreshTokenResponse {
  access_token: string;
  refresh_token: string;
}
