/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo Go Public API
 * Multi-tenant Todo Application with Row Level Security
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  name: string;
}
