/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo Go Public API
 * Multi-tenant Todo Application with Row Level Security
 * OpenAPI spec version: 1.0.0
 */

export interface TodoResponse {
  id: string;
  user_id: string;
  title: string;
  description: string;
  completed: boolean;
  is_public: boolean;
  /** @nullable */
  due_date?: string | null;
  /** @nullable */
  completed_at?: string | null;
  created_at: string;
  updated_at: string;
}
