/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo Go Public API
 * Multi-tenant Todo Application with Row Level Security
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTodoRequest {
  title: string;
  description?: string;
  completed: boolean;
  is_public?: boolean;
  /** @nullable */
  due_date?: string | null;
}
