/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo Go Public API
 * Multi-tenant Todo Application with Row Level Security
 * OpenAPI spec version: 1.0.0
 */

export type UserResponseRole = typeof UserResponseRole[keyof typeof UserResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRole = {
  admin: 'admin',
  member: 'member',
} as const;
