/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Good Todo Go Public API
 * Multi-tenant Todo Application with Row Level Security
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseRole } from './userResponseRole';

export interface UserResponse {
  id: string;
  tenant_id: string;
  email: string;
  name: string;
  role: UserResponseRole;
  email_verified: boolean;
  created_at: string;
  updated_at: string;
}
