// Code generated by MockGen. DO NOT EDIT.
// Source: tenant.go
//
// Generated by this command:
//
//	mockgen -source=tenant.go -destination=mock/tenant.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "good-todo-go/internal/domain/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITenantRepository is a mock of ITenantRepository interface.
type MockITenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITenantRepositoryMockRecorder
	isgomock struct{}
}

// MockITenantRepositoryMockRecorder is the mock recorder for MockITenantRepository.
type MockITenantRepositoryMockRecorder struct {
	mock *MockITenantRepository
}

// NewMockITenantRepository creates a new mock instance.
func NewMockITenantRepository(ctrl *gomock.Controller) *MockITenantRepository {
	mock := &MockITenantRepository{ctrl: ctrl}
	mock.recorder = &MockITenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITenantRepository) EXPECT() *MockITenantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITenantRepository) Create(ctx context.Context, tenant *model.Tenant) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenant)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITenantRepositoryMockRecorder) Create(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITenantRepository)(nil).Create), ctx, tenant)
}

// FindByID mocks base method.
func (m *MockITenantRepository) FindByID(ctx context.Context, id string) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockITenantRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockITenantRepository)(nil).FindByID), ctx, id)
}

// FindBySlug mocks base method.
func (m *MockITenantRepository) FindBySlug(ctx context.Context, slug string) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockITenantRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockITenantRepository)(nil).FindBySlug), ctx, slug)
}
